import Head from "next/head";
import {
  Container,
  Breadcrumb,
  BreadcrumbItem,
  Col,
  Row,
  Button,
  Form,
  FormGroup,
  Label,
  Input,
  Card,
  InputGroup,
  InputGroupAddon
} from "reactstrap";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
// import { fazz} from '@fortawesome/free-brands-svg-icons'
import { faInstagram, faYoutube, faTwitterSquare, faFacebookSquare } from '@fortawesome/free-brands-svg-icons'

import NavbarHome from '../components/navbar-home/index'

export default function Home() {

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <NavbarHome />

      <Container className="container-registrasi">
        <Breadcrumb>
          <BreadcrumbItem>
            <a href="#">Home</a>
          </BreadcrumbItem>
          <BreadcrumbItem>
            <a href="#">Lowongan</a>
          </BreadcrumbItem>
          <BreadcrumbItem active>Registrasi</BreadcrumbItem>
        </Breadcrumb>
      </Container>

      <Container className='container-formulir'>
        <h1 className="text-center">
          FORMULIR REGISTRASI MAGANG JASA MARGA
        </h1>

        <div className="data-diri">
          <h3>Data Diri</h3>
          <Form className='form-data-diri'>
            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Nama Lengkap<span>*</span>
                  </Label>
                  <Col className="col-input" md={8}>
                    <Input
                      type="text"
                      name="namaLengkap"
                      id="namaLengkap"
                    // placeholder="Cnth : Adi Supardi"
                    />
                  </Col>
                </FormGroup>
              </Col>
              <Col className="col-right" md={6}>
                <FormGroup row>
                  <Label for="noKtp" md={4}>
                    Nomor KTP<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input
                      type="text"
                      name="noKtp"
                      id="noKtp"
                    // placeholder="cnth 1xxxxx"
                    />
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className='col-left' md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Jenis Kelamin<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="select" name="select" id="exampleSelect">
                      <option>Laki-laki</option>
                      <option>Perempuan</option>
                    </Input>
                  </Col>
                </FormGroup>
              </Col>
              <Col classNam='col-right' md={6}>
                <FormGroup row>
                  <Label for="noKtp" md={4}>
                    Cari KTP<span style={{ color: 'red' }}>*</span>
                  </Label>
                  <Col md={8}>
                    <InputGroup>
                      <Input />
                      <InputGroupAddon addonType="append">
                        <Button color="secondary">Cari</Button>
                      </InputGroupAddon>
                    </InputGroup>
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Tempat lahir<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="text" name="select" id="exampleSelect"></Input>
                  </Col>
                </FormGroup>
              </Col>
              <Col className="col-right" md={6}>
                <FormGroup row>
                  <Label for="noKtp" md={4}>
                    Nama Bank Akun<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input
                      type="text"
                      name="noKtp"
                      id="noKtp"
                    // placeholder="cnth 1xxxxx"
                    />
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Tanggal lahir<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="date" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
              <Col className="col-right" md={6}>
                <FormGroup row>
                  <Label for="noKtp" md={4}>
                    Nama Bank Akun<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input
                      type="text"
                      name="noKtp"
                      id="noKtp"
                    // placeholder="cnth 1xxxxx"
                    />
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Agama<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="select" name="select" id="exampleSelect">
                      <option>Islam</option>
                      <option>Katolik</option>
                      <option>Protestan</option>
                      <option>Hindu</option>
                      <option>Budha</option>

                    </Input>
                  </Col>
                </FormGroup>
              </Col>
              <Col className="col-right" md={6}>
                <FormGroup row>
                  <Label for="noKtp" md={4}>
                    Alamat Domisili<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input
                      type="textarea"
                      name="noKtp"
                      id="noKtp"
                    // placeholder="cnth 1xxxxx"
                    />
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Email<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="text" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    No Hp<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="text" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
            </Row>
          </Form>
        </div>

        <div className="data-pendidikan">
          <h3>Data Pendidikan</h3>
          <Form className="form-pendidikan">
            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Pendidikan<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="select" name="select" id="exampleSelect">
                      <option>SD</option>
                      <option>SMP</option>
                      <option>SMA</option>
                      <option>D3</option>
                      <option>S1</option>
                    </Input>
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Universitas<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="select" name="select" id="exampleSelect">
                      <option>Universitas Indonesia</option>
                      <option>Binus</option>
                      <option>Universitas Padjajaran</option>
                      <option>Universitas Gajah Mada</option>
                    </Input>
                  </Col>
                </FormGroup>
              </Col>
              <Col className="col-right" md={6}>
                <FormGroup row>
                  <Label for="noKtp" md={4}>
                    Jurusan <span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input
                      type="text"
                      name="noKtp"
                      id="noKtp"
                    // placeholder="cnth 1xxxxx"
                    />
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Tahun Lulus<span>*</span>
                  </Label>
                  <Col md={8}>
                    <Input type="select" name="select" id="exampleSelect">
                      <option>2018</option>
                      <option>2019</option>
                      <option>2020</option>
                      <option>2021</option>
                    </Input>
                  </Col>
                </FormGroup>
              </Col>
              <Col md={6}>
                <FormGroup row>
                  <Label check md={9}>
                    <Col>
                      <Input type="checkbox" /> Masih berkuliah sampai saat ini
                    </Col>
                  </Label>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col md={{ size: 6, offset: 6 }}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Semester
                  </Label>
                  <Col md={8}>
                    <Input type="date" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
            </Row>
          </Form>
        </div>

        <div className="pengalaman-organisasi">
          <h3>Pengalaman Organisasi</h3>
          <Card>
            <Form className="form-pengalaman-organisasi">
              <Row>
                <Col className="col-left" md={6}>
                  <FormGroup row>
                    <Label for="namaLengkap" md={4}>
                      Organisasi<span>*</span>
                    </Label>
                    <Col md={8}>
                      <Input type="text" name="select" id="exampleSelect">
                      </Input>
                    </Col>
                  </FormGroup>
                </Col>
                <Col className="col-right" md={6}>
                  <FormGroup row>
                    <Label for="noKtp" md={4}>
                      Deskripsi Kegiatan<span>*</span>
                    </Label>
                    <Col md={8}>
                      <Input
                        type="textarea"
                        name="noKtp"
                        id="noKtp"
                        placeholder="cnth 1xxxxx"
                      />
                    </Col>
                  </FormGroup>
                </Col>
              </Row>

              <Row>
                <Col className="col-left" md={6}>
                  <FormGroup row>
                    <Label for="namaLengkap" md={4}>
                      Tahun<span>*</span>
                    </Label>
                    <Col md={8}>
                      <Input type="select" name="select" id="exampleSelect">
                        <option>2018</option>
                        <option>2019</option>
                        <option>2020</option>
                        <option>2021</option>
                      </Input>
                    </Col>
                  </FormGroup>
                </Col>
              </Row>

              <Row>
                <Col className="col-left" md={6}>
                  <FormGroup row>
                    <Label for="namaLengkap" md={4}>
                      Jabatan<span>*</span>
                    </Label>
                    <Col md={8}>
                      <Input type="text" name="select" id="exampleSelect"></Input>
                    </Col>
                  </FormGroup>
                </Col>
                <Col className="col-right" md={6}>
                  <FormGroup row>
                    <Label for="namaLengkap" md={4}>
                      File
                    </Label>
                    <Col md={8}>
                      <InputGroup>
                        <Input />
                        <InputGroupAddon addonType="append">
                          <Button color="secondary">Cari</Button>
                        </InputGroupAddon>
                      </InputGroup>
                    </Col>
                  </FormGroup>
                </Col>
              </Row>
            </Form>
          </Card>

        </div>

        <div className="keahlian">
          <h3>Keahlian Yang Dimiliki</h3>
          <Form className="form-keahlian">
            <Row>
              <Col className='col-left' md={12}>
                <FormGroup row>
                  <Label for="namaLengkap" md={2}>
                    Keahlian<span>*</span>
                  </Label>
                  <Col md={10}>
                    <Input type="textarea" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
            </Row>
          </Form>
        </div>

        <div className="lain-lain">
          <h3>Lain-lain</h3>
          <Form className="form-lain-lain">
            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Cv<span>*</span>
                  </Label>
                  <Col md={8}>
                    <InputGroup>
                      <Input />
                      <InputGroupAddon addonType="append">
                        <Button color="secondary">Cari</Button>
                      </InputGroupAddon>
                    </InputGroup>
                  </Col>
                </FormGroup>
              </Col>
              <Col className="col-right" md={6}>
                <FormGroup row>
                  <Label for="noKtp" md={4}>
                    Pas Photo <span>*</span>
                  </Label>
                  <Col md={8}>
                    <InputGroup>
                      <Input />
                      <InputGroupAddon addonType="append">
                        <Button color="secondary">Cari</Button>
                      </InputGroupAddon>
                    </InputGroup>
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Portofolio<span>*</span>
                  </Label>
                  <Col md={8}>
                    <InputGroup>
                      <Input />
                      <InputGroupAddon addonType="append">
                        <Button color="secondary">Cari</Button>
                      </InputGroupAddon>
                    </InputGroup>
                  </Col>
                </FormGroup>
              </Col>
            </Row>
          </Form>
        </div>

        <div className="sosial-media">
          <h3>SOSIAL MEDIA</h3>
          <Form className="form-sosial-media">
            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Linkedin
                  </Label>
                  <Col md={8}>
                    <Input type="text" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
              <Col className="col-right" md={6}>
                <FormGroup row>
                  <Label for="noKtp" md={4}>
                    Instagram
                  </Label>
                  <Col md={8}>
                    <Input
                      type="text"
                      name="noKtp"
                      id="noKtp"
                      // placeholder="cnth 1xxxxx"
                    />
                  </Col>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col className="col-left" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Facebook
                  </Label>
                  <Col md={8}>
                    <Input type="text" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
              <Col className="col-right" md={6}>
                <FormGroup row>
                  <Label for="namaLengkap" md={4}>
                    Twitter
                  </Label>
                  <Col md={8}>
                    <Input type="text" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
            </Row>
          </Form>
        </div>

        <div className="kenal">
          <h3>Mengenal Jasamarga dari ?</h3>
          <Form className="form-kenal">
            <Row>
              <Col md={4}>
                <FormGroup row>
                  <Label check>
                    <Input type="radio" name="radio1" /> Internet
                  </Label>
                </FormGroup>
              </Col>
              <Col md={4}>
                <FormGroup row>
                  <Label check>
                    <Input type="radio" name="radio1" /> Instagram
                  </Label>
                </FormGroup>
              </Col>
              <Col md={4}>
                <FormGroup row>
                  <Label check>
                    <Input type="radio" name="radio1" /> Twitter
                  </Label>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col md={4}>
                <FormGroup row>
                  <Label check>
                    <Input type="radio" name="radio1" /> Kampus
                  </Label>
                </FormGroup>
              </Col>
              <Col md={4}>
                <FormGroup row>
                  <Label check>
                    <Input type="radio" name="radio1" /> Facebook
                  </Label>
                </FormGroup>
              </Col>
              <Col md={4}>
                <FormGroup row>
                  <Label check>
                    <Input type="radio" name="radio1" /> Twitter
                  </Label>
                </FormGroup>
              </Col>
            </Row>

            <Row>
              <Col md={{ size: 4, offset: 8 }}>
                <FormGroup row>
                  <Col md={12}>
                    <Input type="text" name="select" id="exampleSelect" />
                  </Col>
                </FormGroup>
              </Col>
            </Row>
          </Form>
        </div>

        <Row className="justify-content-center align-items-center">
          <Col className="text-center" md={12}>
            <p>
              1.
              .................................................................................................................................................................................
            </p>
            <p>
              2.
              .................................................................................................................................................................................
            </p>
            <p>
              3.
              .................................................................................................................................................................................
            </p>
          </Col>
        </Row>

        <Row className="s-dan-k justify-content-center align-items-center">
          <Col className="col text-center" md={12}>
            <FormGroup check>
              <Label check>
                <Input type="checkbox" /> Dengan ini saya menyetujui syarat dan ketentuan Magang yang ada di PT Jasa Marga (Persero) Tbk.
              </Label>
            </FormGroup>
          </Col>
        </Row>

        <Row className="row-button justify-content-center align-items-center">
          <Button>Kirim Lamaran</Button>
        </Row>
      </Container>

      <Container fluid className="container-footer">
        <Row className="justify-content-between">
          <div className="col-left">
            <p>PT Jasa Marga (Persero) Tbk </p>
          </div>

          <div className="row row-right align-items-center">
            <Col> <FontAwesomeIcon style={{ width: '40px', height: '40px' }} icon={faInstagram} /></Col>
            <Col> <FontAwesomeIcon style={{ width: '40px', height: '40px' }} icon={faTwitterSquare} /></Col>
            <Col> <FontAwesomeIcon style={{ width: '40px', height: '40px' }} icon={faFacebookSquare} /></Col>
            <Col> <FontAwesomeIcon style={{ width: '40px', height: '40px' }} icon={faYoutube} /></Col>
          </div>

        </Row>

      </Container>
    </>
  );
}
